# Generated by Django 4.1.3 on 2023-02-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addblog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('Decri', models.CharField(max_length=255)),
                ('p_url', models.CharField(max_length=255)),
                ('Img', models.ImageField(upload_to='add_images')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=255)),
                ('L_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
